import { loginPortalAccount, getStoredR20PortalSession } from "./r20PortalAuthClient.js";
export const R20_PORTAL_LOGIN_BRIDGE_MARKER="R20_AUDIT_PHASES_01_08_PORTAL_LOGIN_BRIDGE_V1";
const APP_AUTH_KEY="mobdea_mobile_auth_v2";let panel=null;
const clean=v=>String(v??"").trim();
function teacher(){try{const a=JSON.parse(localStorage.getItem(APP_AUTH_KEY)||"null");return ["admin","teacher"].includes(a?.role)&&Number(a.expiresAt||0)>Date.now();}catch{return false;}}
function appSession(s){if(!["student","parent"].includes(s?.role))return;localStorage.setItem(APP_AUTH_KEY,JSON.stringify({role:s.role,name:s.displayName||"",expiresAt:Date.now()+43200000,r20Portal:true,accountId:s.accountId,studentId:s.studentId||null,linkedStudentIds:s.linkedStudentIds||[]}));}
function loginScreen(){if(document.querySelector(".dashboard-v103,[data-dashboard]"))return false;const t=clean(document.body?.textContent).toLowerCase();return /تسجيل الدخول|دخول|login|sign in/.test(t)||Boolean(document.querySelector('input[type="password"]'));}
function make(){const s=document.createElement("section");s.className="r20-portal-login";s.dataset.r20PortalLogin="true";s.innerHTML=`<form class="r20-portal-login__card"><h2>دخول الطالب / ولي الأمر</h2><div class="r20-portal-login__roles"><label><input type="radio" name="role" value="student" checked> طالب</label><label><input type="radio" name="role" value="parent"> ولي أمر</label></div><label><span data-r20-login-id-label>كود الطالب</span><input name="accountId" autocomplete="username" required></label><label>كلمة المرور<input name="password" type="password" autocomplete="current-password" required></label><p class="r20-portal-login__error" aria-live="polite"></p><button type="submit">دخول</button></form>`;const f=s.querySelector("form"),lab=s.querySelector("[data-r20-login-id-label]"),err=s.querySelector(".r20-portal-login__error");f.addEventListener("change",()=>lab.textContent=new FormData(f).get("role")==="parent"?"رقم ولي الأمر":"كود الطالب");f.addEventListener("submit",async e=>{e.preventDefault();const d=new FormData(f),btn=f.querySelector("button");btn.disabled=true;err.textContent="";try{const session=await loginPortalAccount({role:clean(d.get("role")),accountId:clean(d.get("accountId")),password:clean(d.get("password"))});if(!session.mustChangePassword){appSession(session);location.reload();}}catch(x){err.textContent=x?.message||"تعذر تسجيل الدخول.";}finally{btn.disabled=false;}});return s;}
function run(){if(teacher()){panel?.remove();panel=null;return;}const ps=getStoredR20PortalSession();if(ps?.canAccessPortal){appSession(ps);return;}if(!loginScreen()||document.querySelector("[data-r20-portal-login='true']"))return;panel=make();(document.querySelector(".login-page,.login-card,[data-login-page],main")||document.body).appendChild(panel);}
export function installR20PortalLoginBridge(){if(typeof window==="undefined"||typeof document==="undefined"||window.__MOBDEA_R20_PORTAL_LOGIN_BRIDGE__)return;window.__MOBDEA_R20_PORTAL_LOGIN_BRIDGE__=R20_PORTAL_LOGIN_BRIDGE_MARKER;window.addEventListener("mobdea:r20-password-changed",e=>{const s=e.detail||getStoredR20PortalSession();if(s?.canAccessPortal){appSession(s);location.reload();}});let q=false;const schedule=()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;run();});};new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});run();}
if(typeof window!=="undefined"){if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",installR20PortalLoginBridge,{once:true});else installR20PortalLoginBridge();}
