export const R20_MAP_CHALLENGE_CONFIG_MARKER = "R20_FIX15_MAP_CHALLENGE_CONFIG_V1";
export const R20_MAP_CHALLENGE_PATH = "active:mapChallenge";
export const R20_MAP_CHALLENGE_HAS_NATIVE_GESTURES = true;
export const R20_MAP_CHALLENGE_HAS_LAYER_LOGIC = true;
export const R20_MAP_CHALLENGE_SOURCE_COUNT = 26;
