export const R20_MONTHLY_EVALUATION_CONFIG_MARKER = "R20_FIX25_MONTHLY_EVALUATION_CONFIG_V1";
export const R20_MONTHLY_LEGACY_MONTHLY_FOUND = false;
export const R20_MONTHLY_HAS_RANKING = true;
export const R20_MONTHLY_HAS_CLASS_POINTS = true;
export const R20_MONTHLY_HAS_GROUPS = true;
export const R20_MONTHLY_SOURCE_COUNT = 6;
