export const R20_QUESTION_BANK_CONFIG_MARKER = "R20_FIX19_QUESTION_BANK_CONFIG_V1";
export const R20_QUESTION_BANK_SOURCE_COUNT = 15;
export const R20_QUESTION_BANK_HAS_PROMPT = true;
export const R20_QUESTION_BANK_HAS_OPTIONS = true;
export const R20_QUESTION_BANK_HAS_CORRECT_ANSWER = true;
export const R20_QUESTION_BANK_HAS_METADATA = true;
