export const R20_REPORTS_WHATSAPP_CONFIG_MARKER = "R20_FIX21_REPORTS_WHATSAPP_CONFIG_V1";
export const R20_REPORTS_HAS_EXAM_RESULTS = true;
export const R20_REPORTS_HAS_PARENT_PHONE = true;
export const R20_REPORTS_HAS_LINKED_STUDENTS = true;
export const R20_REPORTS_HAS_PORTAL_PERMISSION = true;
