export const R20_REMEDIAL_ASSISTANT_CONFIG_MARKER = "R20_FIX22_REMEDIAL_ASSISTANT_CONFIG_V1";
export const R20_REMEDIAL_HAS_QUESTION_QUERY = true;
export const R20_REMEDIAL_HAS_QUESTION_TAKE = true;
export const R20_REMEDIAL_HAS_WEAKNESS = true;
export const R20_REMEDIAL_HAS_ATTEMPTS = true;
export const R20_REMEDIAL_HAS_REPORTS = true;
export const R20_REMEDIAL_HAS_ASSISTANT_DASHBOARD = true;
